[2024-10-27T21:11:31.644+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holiday_etl_pipeline.load_to_bronze manual__2024-10-27T20:30:56.364990+00:00 [queued]>
[2024-10-27T21:11:31.650+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holiday_etl_pipeline.load_to_bronze manual__2024-10-27T20:30:56.364990+00:00 [queued]>
[2024-10-27T21:11:31.650+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-27T21:11:31.659+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_to_bronze> on 2024-10-27 20:30:56.364990+00:00
[2024-10-27T21:11:31.664+0000] {standard_task_runner.py:60} INFO - Started process 72 to run task
[2024-10-27T21:11:31.666+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'holiday_etl_pipeline', 'load_to_bronze', 'manual__2024-10-27T20:30:56.364990+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/holidays_orchestror.py', '--cfg-path', '/tmp/tmplqv8nfby']
[2024-10-27T21:11:31.668+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask load_to_bronze
[2024-10-27T21:11:31.707+0000] {task_command.py:423} INFO - Running <TaskInstance: holiday_etl_pipeline.load_to_bronze manual__2024-10-27T20:30:56.364990+00:00 [running]> on host d651bf943efd
[2024-10-27T21:11:31.772+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='holiday_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T20:30:56.364990+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T20:30:56.364990+00:00'
[2024-10-27T21:11:31.774+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/holidays_orchestror.py", line 45, in process_bronze
    file_path=landing_result["file_path"],
              ~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-27T21:11:31.782+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=holiday_etl_pipeline, task_id=load_to_bronze, execution_date=20241027T203056, start_date=20241027T211131, end_date=20241027T211131
[2024-10-27T21:11:31.790+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task load_to_bronze ('NoneType' object is not subscriptable; 72)
[2024-10-27T21:11:31.799+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-27T21:11:31.816+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
